//! Self-verifying shell-script exporter.

use chrono::Utc;
use sha2::{Digest, Sha256};

use crate::optimizer::OptimizationAction;

pub struct ShellExport;

impl ShellExport {
    pub fn render(actions: &[OptimizationAction], device_label: &str) -> String {
        let body = render_body(actions);
        let hash = hex::encode(Sha256::digest(body.as_bytes()));
        let when = Utc::now().to_rfc3339();

        let mut s = String::new();
        s.push_str("#!/usr/bin/env sh\n");
        s.push_str("# Generated by DozeForge -- do not edit.\n");
        s.push_str(&format!("# Device: {device_label}\n"));
        s.push_str(&format!("# Generated: {when}\n"));
        s.push_str(&format!("# BODY_SHA256={hash}\n"));
        s.push('\n');
        s.push_str("set -eu\n");
        s.push_str(SELF_CHECK_PREAMBLE);
        s.push_str("\n# ===== BODY START =====\n");
        s.push_str(&body);
        s.push_str("# ===== BODY END =====\n");
        s
    }
}

fn render_body(actions: &[OptimizationAction]) -> String {
    let mut body = String::new();
    for action in actions {
        body.push_str(&action.to_shell());
        body.push('\n');
    }
    body
}

const SELF_CHECK_PREAMBLE: &str = r#"
expected_hash=$(grep '^# BODY_SHA256=' "$0" | head -n1 | sed 's/^# BODY_SHA256=//')
body=$(awk '/^# ===== BODY START =====$/{flag=1; next} /^# ===== BODY END =====$/{flag=0} flag' "$0")
actual_hash=$(printf "%s" "$body" | sha256sum | awk '{print $1}')
if [ "$expected_hash" != "$actual_hash" ]; then
  echo "DozeForge: integrity check FAILED" >&2
  echo "  expected: $expected_hash" >&2
  echo "  actual:   $actual_hash" >&2
  exit 78
fi
"#;
